# Generated by Django 3.2 on 2021-07-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_app',
            new_name='created_at',
        ),
    ]
