# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 599)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.input = QtWidgets.QLineEdit(self.centralwidget)
        self.input.setText("")
        self.input.setClearButtonEnabled(True)
        self.input.setObjectName("input")
        self.gridLayout.addWidget(self.input, 2, 0, 1, 1)

        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setObjectName("send")
        self.gridLayout.addWidget(self.send, 2, 1, 1, 1)

        self.msg_area = QtWidgets.QScrollArea(self.centralwidget)
        self.msg_area.setWidgetResizable(True)
        self.msg_area.setObjectName("msg_area")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 907, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")

        self.gridLayout.addWidget(self.msg_area, 0, 0, 1, 2)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.send.clicked.connect(self.pressed)
        self.input.returnPressed.connect(self.pressed)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input.setToolTip(_translate("MainWindow", "Type text here and hit enter"))
        self.input.setPlaceholderText(_translate("MainWindow", "Type text here and hit enter."))
        self.send.setText(_translate("MainWindow", "Send"))

    def pressed(self):
        if txt := self.input.text():
            self.input.setText("")
            self.print_message(txt)

    def _get_new_label(self):
        label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        label.setMaximumSize(QtCore.QSize(16777215, 50))
        label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        label.setFont(font)
        label.setObjectName("label")
        self.verticalLayout.addWidget(label)
        self.msg_area.setWidget(self.scrollAreaWidgetContents)

        return label

    def print_message(self, msg):
        label = self._get_new_label()
        label.setText(msg)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
