# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(4, -5, 791, 521))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../../../../Real_Wallpapers/2.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.Image1 = QtWidgets.QPushButton(self.centralwidget)
        self.Image1.setGeometry(QtCore.QRect(100, 540, 311, 51))
        self.Image1.setObjectName("Image1")
        self.Image2 = QtWidgets.QPushButton(self.centralwidget)
        self.Image2.setGeometry(QtCore.QRect(430, 540, 231, 51))
        self.Image2.setObjectName("Image2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Image1.clicked.connect(self.show_1)
        self.Image2.clicked.connect(self.show_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Image1.setText(_translate("MainWindow", "Image 1"))
        self.Image2.setText(_translate("MainWindow", "Image 2"))

    def show_1(self):
        self.photo.setPixmap(QtGui.QPixmap("../../../../../Real_Wallpapers/1.jpg"))

    def show_2(self):
        self.photo.setPixmap(QtGui.QPixmap("../../../../../Real_Wallpapers/2.jpg"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
